image: mcr.microsoft.com/dotnet/sdk:7.0
stages:
  - build

build-job:
  stage: build
  tags:
    - shared-fi
  script:
    - dotnet restore
    - dotnet build
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
