services:
  web:
    build:
      dockerfile: ./BenchStoreMVC/Dockerfile
    container_name: BenchStore-web
    restart: always
    environment:
      ConnectionStrings__BenchStoreContext: "Host=BenchStore-db; Database=${POSTGRES_DB}; Username=${POSTGRES_USER}; Password=${POSTGRES_PASSWORD}"
      TableGenerator__PythonPath: /usr/bin/python
      TableGenerator__TableGeneratorPath: /usr/bin/table-generator
      Storage__ResultStoragePath: /app/wwwroot/result-storage
    volumes:
      - result-storage:/app/result-storage
    ports:
      - 15142:80

  database:
    image: docker.io/postgres:16-alpine
    container_name: BenchStore-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - database-persistence:/var/lib/postgresql/data
    ports:
      - 15143:5432

volumes:
  database-persistence:
  result-storage:
